[package]
name = "convert_fahranheit_celsius"
version = "0.1.0"
authors = ["Justine <brunjustin@eisti.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
